Myprofile/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('fa',include('homeFa.urls')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns=[
    path('',views.home,name='home'),
]

homeFa/urls.py
from django.urls import path
from . import views


app_name='homeFa'
urlpatterns=[
    path('',views.home_fa,name='home'),
]

home/models.py
from django.db import models


# header

class Header(models.Model):
    name = models.CharField(max_length=75)
    position = models.CharField(max_length=75)
    img = models.ImageField('img/home')

    def __str__(self):
        return 'Header'


# About Me section

class AboutMe(models.Model):
    info = models.TextField()
    email = models.CharField(max_length=95)
    phone = models.CharField(max_length=15)

    def __str__(self):
        return 'About Me'


# Social Media

class SocialMedia(models.Model):
    linkedin = models.CharField(max_length=100)
    github = models.CharField(max_length=100)
    twitter = models.CharField(max_length=100)
    telegram = models.CharField(max_length=100)
    whatsapp = models.CharField(max_length=100)
    instagram = models.CharField(max_length=100)

    def __str__(self):
        return 'Social Media'


# Tecnology

class Technology(models.Model):
    img = models.ImageField('img/Technology')
    name = models.CharField(max_length=25)
    level = models.CharField(max_length=25)

    def __str__(self):
        return f'{self.name} - {self.level}'


# Tools

class Tools(models.Model):
    img = models.ImageField('img/Tools')
    name = models.CharField(max_length=25)
    level = models.CharField(max_length=25)

    def __str__(self):
        return f'{self.name} - {self.level}'


# Other Skills

class OtherSkills(models.Model):
    tittle = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.tittle}'


# Projects

class Project(models.Model):
    img = models.ImageField('img/Project')
    tittle = models.CharField(max_length=25)
    description = models.CharField(max_length=100)
    tech = models.ManyToManyField(Technology)
    code = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.tittle}'


# Ticket

class Ticket(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    message = models.TextField()
    crete = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} - {self.message} -{self.crete}'

homeFa/models.py
from django.db import models


# header

class Header(models.Model):
    name = models.CharField(max_length=75)
    position = models.CharField(max_length=75)
    img = models.ImageField('img/home')

    def __str__(self):
        return 'Header'


# About Me section

class AboutMe(models.Model):
    info = models.TextField()
    email = models.CharField(max_length=95)
    phone = models.CharField(max_length=15)

    def __str__(self):
        return 'About Me'


# Tecnology


class Technology(models.Model):
    img = models.ImageField('img/Technology')
    name = models.CharField(max_length=25)
    level = models.CharField(max_length=25)

    def __str__(self):
        return f'{self.name} - {self.level}'


# Tools

class Tools(models.Model):
    img = models.ImageField('img/Tools')
    name = models.CharField(max_length=25)
    level = models.CharField(max_length=25)

    def __str__(self):
        return f'{self.name} - {self.level}'


# Other Skills

class OtherSkills(models.Model):
    tittle = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.tittle}'


# Projects

class Project(models.Model):
    img = models.ImageField('img/Project')
    tittle = models.CharField(max_length=25)
    description = models.CharField(max_length=100)
    tech = models.ManyToManyField(Technology)
    code = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.tittle}'

home/views.py
from django.shortcuts import render
from . import models
import telebot



def home(request):
    header = models.Header.objects.last()
    aboutMe = models.AboutMe.objects.last()
    socialMedia = models.SocialMedia.objects.last()
    technologys = models.Technology.objects.all()
    projects=models.Project.objects.all()
    tools = models.Tools.objects.all()
    otherSkills = models.OtherSkills.objects.all()

    if request.method=="POST":
        name=request.POST.get('fullName')
        email=request.POST.get('email')
        message=request.POST.get('message')
        models.Ticket.objects.create(name=name,email=email,message=message)
        bot = telebot.TeleBot('7008384349:AAHiFpu3vwi310YOQrTQBMlsEf34cjVoQ48')
        bot.send_message(149539081, 'You have New Ticket')
    return render(request, 'home/index.html', context={'header': header, 'aboutMe': aboutMe, 'socialMedia': socialMedia,
                                                       'technologys': technologys, 'tools': tools,
                                                       'otherSkills': otherSkills,'projects':projects})

homeFa/views.py
from django.shortcuts import render,redirect
from . import models
from home.models import Ticket, SocialMedia
import telebot


def home_fa(request):
    header = models.Header.objects.last()
    aboutMe = models.AboutMe.objects.last()
    socialMedia = SocialMedia.objects.last()
    technologys = models.Technology.objects.all()
    tools = models.Tools.objects.all()
    otherSkills = models.OtherSkills.objects.all()
    projects = models.Project.objects.all()
    
    if request.method == "POST":
        name = request.POST.get('fullName')
        email = request.POST.get('email')
        message = request.POST.get('message')
        Ticket.objects.create(name=name, email=email, message=message)
        bot = telebot.TeleBot('7008384349:AAHiFpu3vwi310YOQrTQBMlsEf34cjVoQ48')
        bot.send_message(149539081, 'You have New Ticket')
        return redirect('homeFa:home')
    return render(request, 'homeFa/fa.html',
                  context={'header': header, 'aboutMe': aboutMe, 'technologys': technologys, 'socialMedia': socialMedia,
                           'tools': tools, 'otherSkills': otherSkills,'projects':projects})

home/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Asem.bq</title>
    <link
            rel="shortcut icon"
            href="{% static 'icon/fav.ico' %}"
            type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'css/index.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/contactme.css' %}">
</head>
<body>
<!-- header -->

<header class="header">
    <img src="{{ header.img.url }}" alt="Asem"/>
    <div class="titel">
        <h1>{{ header.name }}</h1>
        <h2 class="position">
            <i class="fa-solid fa-angle-right"></i> {{ header.position }}
        </h2>
        <a href="{{ socialMedia.github }}" target="_blank" class="button"
        ><i class="fa-brands fa-github"></i> My Github Profile</a
        >
    </div>
    <a href="{% url 'homeFa:home' %}" class="lang"><i class="fa-solid fa-globe"></i> Fa</a>
</header>

<div class="countainer">
    <!-- Nav bar -->

    <nav>
        <ul>
            <li class="active AboutMe">
                <span class="marker"><i class="fa-solid fa-angle-right"></i></span>
                About Me
            </li>
            <li class="MySkilles">
                <span class="marker"><i class="fa-solid fa-angle-right"></i></span>
                My Skills
            </li>
            <li class="MyProject">
                <span class="marker"><i class="fa-solid fa-angle-right"></i></span>
                My Project
            </li>
            <li id="ContactMe" class="">
                <span class="marker"><i class="fa-solid fa-angle-right"></i></span>
                Contact Me
            </li>
        </ul>
    </nav>

    <!-- section -->

    <section class="sections">
        <section class="active AboutMe">
            <h4>About Me</h4>
            <p>
                {{ aboutMe.info }}
            </p>

            <div class="contact">
                <div class="email">
                    <h5>Email</h5>
                    <p>{{ aboutMe.email }} <i class="fa-regular fa-clone"></i></p>
                </div>
                <div class="number">
                    <h5>Phone</h5>
                    <p>{{ aboutMe.phone }}<i class="fa-regular fa-clone"></i></p>
                </div>
            </div>

            <h5>Social Media</h5>
            <ul class="social">
                <li>
                    <a
                            target="_blank"
                            href="{{ socialMedia.linkedin }}"
                    ><span class="linkedin"></span
                    ></a>
                </li>
                <li>
                    <a target="_blank" href="{{ socialMedia.github }}"
                    ><span class="github"></span
                    ></a>
                </li>
                <li>
                    <a
                            target="_blank"
                            href="{{ socialMedia.twitter }}"
                    ><span class="twitter"></span
                    ></a>
                </li>
                <li>
                    <a target="_blank" href="{{ socialMedia.telegram }}"
                    ><span class="telegram"></span
                    ></a>
                </li>
                <li>
                    <a target="_blank" href="{{ socialMedia.whatsapp }}"
                    ><span class="whatsup"></span
                    ></a>
                </li>
                <li>
                    <a target="_blank" href="{{ socialMedia.instagram }}"
                    ><span class="instagram"></span
                    ></a>
                </li>
            </ul>
        </section>

        <!-- section -->
        <section class="Tecnology">
            <h4>Technology</h4>
            <ul class="skilles">

                {% for technology in technologys %}

                    <li>
              <span class="left"
              ><img src="{{ technology.img.url }}" alt=""/> {{ technology.name }}</span
              >
                        <span class="right" style="text-align: center;"
                        >{{ technology.level }}</span
                        >
                    </li>
                {% endfor %}
            </ul>
            <h4>Tools</h4>
            <ul class="skilles">
                {% for tool in tools %}
                    <li>
              <span class="left"
              ><img src="{{ tool.img.url }}" alt=""/> {{ tool.name }} </span
              ><span class="right"
                    >{{ tool.level }}</span
                    >
                    </li>
                {% endfor %}
            </ul>
            <h4>Other Skills</h4>
            <ul class="other_skilles">
                {% for otherSkill in otherSkills %}
                    <li> {{ otherSkill.tittle }}</li>
                {% endfor %}

            </ul>
        </section>

        <!-- section -->
        <section id="MyProject" class="MyProject">
            <h4>My Project</h4>
            <div class="projects">
                {% for project in projects %}
                	<div class="project">
                    <div class="top">
                        <img src="{{ project.img.url }}" alt=""/>
                        <h6 class="titel">{{ project.tittle }}</h6>
                    </div>
                    <div class="midel">
                        <p>
                            {{ project.description }}
                        </p>
                    </div>
                    <div class="bottom">
                        <div class="tech">
                            tech used:
                            <ul>
                                {% for tech in project.tech.all %}
                                	<li><img src="{{ tech.img.url }}" alt=""/></li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="buttons">
                            <a target="_blank" href="./franchis.html"
                            ><i class="fa-solid fa-eye"></i>Demo</a
                            >
                            <a target="_blank" href="https://github.com/AsemBq/franchise"
                            ><i class="fa-brands fa-github"></i>View Code</a
                            >
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </section>

        <section class="ContactMe">
            <h4>Contact Me</h4>
            <div class="container">
                <form method="post">
                    {% csrf_token %}
                    <div class="input-group input-group-icon">
                        <input name="fullName" type="text" placeholder="Full Name" maxlength="50">
                        <div class="input-icon"><i class="fa-solid fa-user"></i></div>
                    </div>
                    <div class="input-group input-group-icon">
                        <input name="email" type="email" placeholder="Email Address" maxlength="50">
                        <div class="input-icon"><i class="fa fa-envelope"></i></div>
                    </div>
                    <div class="input-group input-group-icon">
                        <textarea name="message" id="" rows="10" placeholder="Message..."></textarea>
                        <div class="input-icon"><i class="fa-solid fa-comment"></i></div>
                    </div>
                    <input id="button" type="submit" value="Send">
                </form>
            </div>
        </section>
    </section>
</div>
<nav class="mobile-nav">
    <ul>
        <li id="About" class="active">
            <i class="fa-regular fa-user"></i>About
        </li>
        <li id="Skilles"><i class="fa-solid fa-code"></i>Skills</li>
        <li id="projects"><i class="fa-solid fa-laptop-code"></i>projects</li>
        <li id="liContact"><i class="fa-solid fa-phone"></i>Contact</li>
    </ul>
</nav>

<script src="{% static 'js/index.js' %}"></script>
</body>
</html>

homeFa/templates/homeFa/fa.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Asem.bq</title>
    <link
      rel="shortcut icon"
      href="{% static 'icon/fav.ico' %}"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'css/fa.css' %}" />
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/responsive-fa.css' %}" />
    <link rel="stylesheet" href="{% static 'css/contactme-fa.css' %}" />
  </head>
  <body>
    <!-- header -->

    <header class="header">
      <div class="titel">
        <h1>{{ header.name }}</h1>
        <h2 class="position">
          {{ header.position }}
          <i class="fa-solid fa-angle-left"></i>
        </h2>
        <a href="{{ socialMedia.github }}" target="_blank" class="button"
          ><i class="fa-brands fa-github"></i> گیت هاب من</a
        >
      </div>
      <img src="{{ header.img.url }}" alt="Asem" />
      <a href="{% url 'home:home' %}" class="lang"
        ><i class="fa-solid fa-globe"></i> En</a
      >
    </header>

    <div class="countainer">
      <!-- section -->

      <section class="sections">
        <section class="AboutMe active">
          <h4>درباره من</h4>
          <p>
               {{ aboutMe.info }}
          </p>
          <div class="contact">
            <div class="email">
              <h5>ایمیل</h5>
              <p><i class="fa-regular fa-clone"> </i>{{ aboutMe.email }}</p>
            </div>
            <div class="number">
              <h5>شماره تماس</h5>
              <p><i class="fa-regular fa-clone"> </i>{{ aboutMe.phone }}</p>
            </div>
          </div>

          <h5>شبکه های اجتماعی</h5>
          <ul class="social">
            <li>
              <a
                target="_blank"
                href="{{ socialMedia.linkedin }}"
                ><span class="linkedin"></span
              ></a>
            </li>
            <li>
              <a target="_blank" href="{{ socialMedia.github }}"
                ><span class="github"></span
              ></a>
            </li>
            <li>
              <a
                target="_blank"
                href="{{ socialMedia.twitter }}"
                ><span class="twitter"></span
              ></a>
            </li>
            <li>
              <a target="_blank" href="{{ socialMedia.telegram }}"
                ><span class="telegram"></span
              ></a>
            </li>
            <li>
              <a target="_blank" href="{{ socialMedia.whatsapp }}"
                ><span class="whatsup"></span
              ></a>
            </li>
            <li>
              <a target="_blank" href="{{ socialMedia.instagram }}"
                ><span class="instagram"></span
              ></a>
            </li>
          </ul>
        </section>

        <!-- section -->
        <section class="Tecnology">
          <h4>تکنولوژی</h4>
          <ul class="skilles">
            {% for technology in technologys %}
                 <li>
              <span class="left">{{ technology.level }}</span>
              <span class="right"
                >{{ technology.name }}<img src="{{ technology.img.url }}" alt=""
              /></span>
            </li>
                {% endfor %}
          </ul>
          <h4>ابزارها</h4>
          <ul class="skilles">
             {% for tool in tools %}
                     <li>
              <span class="left">{{ tool.level }}</span>
              <span class="right"
                >{{ tool.name }}<img src="{{ tool.img.url }}" alt=""
              /></span>
            </li>
                {% endfor %}
          </ul>
          <h4>مهارت‌های دیگر</h4>
          <ul class="other_skilles">
             {% for otherSkill in otherSkills %}
                    <li> {{ otherSkill.tittle }}</li>
                {% endfor %}
          </ul>
        </section>

        <!-- section -->
        <section id="MyProject" class="MyProject">
          <h4>پروژهای من</h4>
          <div class="projects">
            {% for project in projects %}
                	<div class="project">
                    <div class="top">
                        <img src="{{ project.img.url }}" alt=""/>
                        <h6 class="titel">{{ project.tittle }}</h6>
                    </div>
                    <div class="midel">
                        <p>
                            {{ project.description }}
                        </p>
                    </div>
                    <div class="bottom">
                        <div class="tech">
                            <ul>
                                {% for tech in project.tech.all %}
                                	<li><img src="{{ tech.img.url }}" alt=""/></li>
                                {% endfor %}
                            </ul>
                            :تکنولوژی ها
                        </div>
                        <div class="buttons">
                            <a target="_blank" href="./franchis.html"
                            ><i class="fa-solid fa-eye"></i>دمو</a
                            >
                            <a target="_blank" href="https://github.com/AsemBq/franchise"
                            ><i class="fa-brands fa-github"></i>دیدن کدها</a
                            >
                        </div>
                    </div>
                </div>
                {% endfor %}
          </div>
        </section>

        <section class="ContactMe">
          <h4>ارتباط با من</h4>
          <div class="container">
            <form method="post" action="{% url 'homeFa:home' %}">
                {% csrf_token %}
              <div class="input-group input-group-icon">
                <input  name="fullName" type="text" placeholder="نام"  maxlength="50" />
                <div class="input-icon"><i class="fa-solid fa-user"></i></div>
              </div>
              <div class="input-group input-group-icon">
                <input name="email"
                  type="email"
                  placeholder="ایمیل"
                />
                <div class="input-icon"><i class="fa fa-envelope"></i></div>
              </div>
              <div class="input-group input-group-icon">
                <textarea
                  name="message"
                  id=""
                  rows="10"
                  placeholder="پیام..."
                ></textarea>
                <div class="input-icon">
                  <i class="fa-solid fa-comment"></i>
                </div>
              </div>
              <input id="button" type="submit" value="ارسال" />
            </form>
          </div>
        </section>
      </section>

      <!-- Nav bar -->

      <nav>
        <ul>
          <li class="active AboutMe">
            درباره من
            <span class="marker"><i class="fa-solid fa-angle-left"></i></span>
          </li>
          <li class="MySkilles">
            مهارت های من
            <span class="marker"><i class="fa-solid fa-angle-left"></i></span>
          </li>
          <li class="MyProject">
            پروژه های من
            <span class="marker"><i class="fa-solid fa-angle-left"></i></span>
          </li>
          <li id="ContactMe" class="">
            ارتباط با من
            <span class="marker"><i class="fa-solid fa-angle-left"></i></span>
          </li>
        </ul>
      </nav>
    </div>
    <nav class="mobile-nav">
      <ul>
        <li id="About" class="active">
          <i class="fa-regular fa-user"></i>اطلاعات
        </li>
        <li id="Skilles"><i class="fa-solid fa-code"></i>مهارت‌ها</li>
        <li id="projects"><i class="fa-solid fa-laptop-code"></i>پروژها</li>
        <li id="liContact"><i class="fa-solid fa-phone"></i>ارتباط</li>
      </ul>
    </nav>

    <script src="{% static 'js/index.js' %}"></script>
  </body>
</html>